services:
  gdvcsharp-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./app/uploads:/app/uploads
    networks:
      - vulnerable-network
    labels:
      - "description=GDVCSharp Vulnerable Web API for security training"
      - "warning=Contains intentional security vulnerabilities"

  # Optional: Add a simple web server to demonstrate SSRF
  target-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - vulnerable-network
    environment:
      - NGINX_HOST=target-server
      - NGINX_PORT=80

networks:
  vulnerable-network:
    driver: bridge

volumes:
  uploads:
